/// Flutter icons CustomIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/material.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData wallet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = Icons.perm_contact_cal_outlined;

  static const IconData plus = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData market = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountBalanceWallet = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backArrow = IconData(0xf555, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test = Icons.person_add_alt_1_outlined;



}
